add DayDashboard
Sanya486/power-pulse-project pull request #37
Opened 2023-10-23 18:18 UTC by nsihor

2023-10-23 21:46 UTC, demonikos requested changes
потрібно виправити помилки: 
- прокинути пропсами об'єкт/масив;
- повернути проптайси;
- key в li;
- випадаючий марджин на 375

2023-10-24 07:30 UTC, Sanya486 approved these changes

2023-10-24 10:39 UTC, demonikos commented
бачу

2023-10-24 10:39 UTC, demonikos approved these changes

2023-10-24 10:39 UTC, merged