Welcome Page was added
Sanya486/power-pulse-project pull request #72
Opened 2023-10-27 10:03 UTC by ViktoriiaProtasova

2023-10-27 10:19 UTC, ViktoriiaProtasova commented
Додатково додано hover та transition на кнопки Button

2023-10-27 18:41 UTC, demonikos approved these changes
приймаю, але відписав в приватні щоб змінила змінні на веріаблс

2023-10-27 18:41 UTC, demonikos commented on src/components/Header/Header.module.scss
> +@media screen and (max-width: 375px) {
а чому не змінна з variables?)

2023-10-27 18:41 UTC, demonikos commented on src/components/UserNav/UserNav.module.scss
>      color: #efede8;
це теж є в веріаблес

2023-10-27 18:46 UTC, demonikos requested changes
поправити змінні на веріаблс, вирішити меш конфлікт

2023-10-28 11:48 UTC, ViktoriiaProtasova commented on src/components/Header/Header.module.scss
> +@media screen and (max-width: 375px) {
Змінила

2023-10-28 11:50 UTC, ViktoriiaProtasova commented on src/components/UserNav/UserNav.module.scss
>      color: #efede8;
змінила

2023-10-28 11:55 UTC, ViktoriiaProtasova commented
Все виправила.

2023-10-28 13:50 UTC, demonikos approved these changes

2023-10-28 13:50 UTC, merged